export default {
  FETCH_ARTICLES: 'FETCH_ARTICLES',
  FILTER_ARTICLE: 'FILTER_ARTICLE',
  DELETE_ARTICLE: 'DELETE_ARTICLE',
  FETCH_ARTICLES_SUCCESS: 'FETCH_ARTICLES_SUCCESS',
  FETCH_ARTICLES_ERROR: 'FETCH_ARTICLES_ERROR'
}
