export default {
  FETCH_ARTICLES: 'FETCH_ARTICLES',
  FILTER_ARTICLE: 'FILTER_ARTICLE',
  DELETE_ARTICLE: 'DELETE_ARTICLE',
  UPDATE_ARTICLE: 'UPDATE_ARTICLE',
  CREATE_ARTICLE: 'CREATE_ARTICLE',
  DELETE_ARTICLE_SUCCESS: 'DELETE_ARTICLE_SUCCESS',
  FETCH_ARTICLES_SUCCESS: 'FETCH_ARTICLES_SUCCESS',
  DELETE_ARTICLES_SUCCESS: 'DELETE_ARTICLES_SUCCESS',
  UPDATE_ARTICLE_SUCCESS: 'UPDATE_ARTICLE_SUCCESS',
  CREATE_ARTICLE_SUCCESS: 'CREATE_ARTICLE_SUCCESS'
}
